---
title: "Concentration control of the TSOs in the source plates"
output: 
  html_document: 
    fig_height: 5.25
    fig_width: 5.25
    keep_md: yes
    toc: yes
---

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 100)
```


Load scripts and libraries
==========================

```{r load_libraries}
library("magrittr")
library("ggplot2")
# Do not load the whole smallCAGEqc package, just get the barcode data.
data("nanoCAGE2017barcodes", package = "smallCAGEqc")
```


Concentration checks
====================

Data load
---------

Concentrations of the actual TSO solutions in the source plage, measured with
the NanoDrop instrument for 8-strip tubes (NanoDrop 8000 ?).

Concentration factor was _27.8_ (_A260 × 27.8 = concentration_ in ng/μL).

Original file name `180221_KATO.xlsx`.  This file has two sheets.  The first for
source plate 1, where the TSOs at 600 μM were too concentrated for the
measurement (out of dynamic range).  The second is for source plate 1, (first
140 rows), and then for plate 2's TSOs at 600 μM, which were dilluted 5 times
before being measured again.

```{r concentration_QC_load}
conc1 <- gdata::read.xls( "Labcyte-RT2.quantification.xlsx"
                        , nrow = 140, stringsAsFactors = FALSE)
summary(conc1)
conc2 <- gdata::read.xls( "Labcyte-RT2.quantification.xlsx"
                        , nrow = 182, sheet = 2, stringsAsFactors = FALSE)
summary(conc2)
conc1[1:42,] <- conc2[141:182,]
conc2 <- conc2[-(141:182),]
conc2$X <- NA  # For column compatibility with conc1

conc1$exp <- 50
conc1[grep("[1-3]$", conc1$Well), "exp"] <- 600
conc1[grep("[4-6]$", conc1$Well), "exp"] <- 400

conc2$exp <- 50
conc2[grep("[1-3]$", conc2$Well), "exp"] <- 400
conc2[grep("[7-9]$", conc2$Well), "exp"] <- 6.25

conc1$plate <- 2
conc2$plate <- 1
conc <- rbind(conc1, conc2)
rm(conc1); rm(conc2)
```

```{r concentration_QC_prepare}
conc <- data.frame( Well  = conc$Well
                  , plate = conc$plate
                  , exp   = conc$exp
                  , obs   = conc$Conc..
                  , A260  = conc$A260.
                  , A280  = conc$A280.)

summary(conc)

conc <- aggregate(conc[,-1], list(conc$Well, conc$plate, conc$exp), mean)
colnames(conc) <- c("Well", "discard1", "discard2", "plate", "exp", "obs", "A260", "A280")
conc <- conc[,c("Well", "discard1", "discard2", "plate", "exp", "obs", "A260", "A280")]

conc$Well %<>% factor(levels = levels(conc$Well) %>% gtools::mixedsort())
```

Samples at expected 600 μM were diluted 5 times to stay in the instrument's
dynamic range.  Correcting values.

```{r concentration_QC_dil_fact}
conc[conc$exp == 600, c("obs", "A260", "A280")] %<>% multiply_by(5)
```

Histograms
----------

```{r concentration_QC_histograms, warning = FALSE}
hist_obs  <- ggplot(conc, aes(obs,  fill = exp)) + geom_histogram() +
  facet_wrap(~exp, nrow = 1) + ggtitle("Observed concentrations (ng/μL)")
hist_a260 <- ggplot(conc, aes(A260, fill = exp)) + geom_histogram() +
  facet_wrap(~exp, nrow = 1) + ggtitle("Absorbance at 260 nm")
hist_a280 <- ggplot(conc, aes(A280, fill = exp)) + geom_histogram() +
  facet_wrap(~exp, nrow = 1) + ggtitle("Absorbance at 280 nm")

ggpubr::ggarrange( ncol = 1, nrow = 3, hist_obs, hist_a260, hist_a280)
```

Absorbances
-----------

```{r concentration_QC_abs_ratio}
ggplot(conc, aes(A280, A260, colour = exp)) + geom_point() +
    scale_x_log10() + scale_y_log10() +
  ggtitle("Relation between absorbances at 260 and 280 nm")
```

Concentrations
--------------

```{r concentration_QC_obs_exp}
ggplot(conc, aes(exp,  obs, colour = exp))  + geom_point() +
  scale_x_log10() + scale_y_log10() +
  ggtitle("Observed concentration and expected molarity")
```

Session information
===================

```{r sesion_info}
sessionInfo()
```
